name: Publish

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
        
    - name: Build
      run: echo ${{ github.sha }} > Release.txt
    - name: Test
      run: cat Release.txt
        
    - name: Publish win-x64
      run: dotnet publish -p:PublishProfile=win-x64.pubxml Obj2Tiles
    - name: Publish win-arm
      run: dotnet publish -p:PublishProfile=win-arm.pubxml Obj2Tiles
    - name: Publish win-arm64
      run: dotnet publish -p:PublishProfile=win-arm64.pubxml Obj2Tiles
    - name: Publish linux-x64
      run: dotnet publish -p:PublishProfile=linux-x64.pubxml Obj2Tiles
    - name: Publish linux-arm
      run: dotnet publish -p:PublishProfile=linux-arm.pubxml Obj2Tiles
    - name: Publish osx-x64
      run: dotnet publish -p:PublishProfile=osx-x64.pubxml Obj2Tiles  

    - name: Zip win-x64
      run: cd Obj2Tiles/bin/Release/net7.0/publish/win-x64/ && zip -r ../../../../../../Obj2Tiles-Win64.zip *
    - name: Zip win-arm
      run: cd Obj2Tiles/bin/Release/net7.0/publish/win-arm/ && zip -r ../../../../../../Obj2Tiles-WinArm.zip *
    - name: Zip win-arm64
      run: cd Obj2Tiles/bin/Release/net7.0/publish/win-arm64/ && zip -r ../../../../../../Obj2Tiles-WinArm64.zip *
    - name: Zip linux-x64
      run: cd Obj2Tiles/bin/Release/net7.0/publish/linux-x64/ && zip -r ../../../../../../Obj2Tiles-Linux64.zip *
    - name: Zip linux-arm
      run: cd Obj2Tiles/bin/Release/net7.0/publish/linux-arm/ && zip -r ../../../../../../Obj2Tiles-LinuxArm.zip *
    - name: Zip osx-x64
      run: cd Obj2Tiles/bin/Release/net7.0/publish/osx-x64/ && zip -r ../../../../../../Obj2Tiles-Osx64.zip *
      
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          Release.txt
          LICENSE.md
          Obj2Tiles-Win64.zip
          Obj2Tiles-WinArm.zip
          Obj2Tiles-WinArm64.zip
          Obj2Tiles-Linux64.zip
          Obj2Tiles-LinuxArm.zip
          Obj2Tiles-Osx64.zip   
